## np.random.seed(12)

 Seed provide the same random values as before

In [64]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
np.random.seed(12)
np.random.rand(4)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [65]:
# Seed provide the same random values as before
np.random.seed(12)
np.random.rand(4)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [66]:
np.random.seed(10)
np.random.rand(4)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [67]:
np.random.seed(10)
np.random.rand(4)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [73]:
students = np.array(np.random.randint(10))
np.random.choice(students, 5)

array([3, 4, 1, 4, 2])

In [80]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([9, 4, 6, 7, 0, 8, 5, 2, 1, 3])

In [81]:
sample = _
sample.mean()

4.5

## Binomial Distributions

We use binomial probability mass function. To calculate the probability. 


In [147]:
# simulate 100 tests of 1 fair coin flips
tests = np.random.binomial(1, 0.5, 100) 
print((tests == 1).mean())  # Probablity of getting Head in 10 try with a fair coin flip
print((tests == 0).mean())  # Probablity of getting Tail in 10 try with a fair coin flip
# Probablity of getting atleast 3 Head in 10 try with a fair coin flip

0.52
0.48


In [148]:
# simulate 100 tests of five fair coin flips
tests = np.random.binomial(5, 0.5, 100)

(tests == 1).mean()  # Probablity of getting only 1 Head in 5 try with a fair coin flip

0.16

In [149]:
# simulate 1 million tests of five biased coin flips
tests = np.random.binomial(5, 0.8, int(1e6))

# proportion of tests that produced 5 heads
(tests == 5).mean()

0.327096

Estimate the probability of having up to 4 successful bets after the 15th. So the final probability will be the sum of the probability to get 0 successful bets in 15 bets, plus the probability to get 1 successful bet, ..., to the probability of having 4 successful bets in 15 bets.

In [106]:
import scipy.stats as ss

n = 15         # Number of total bets
p = 18./38     # Probability of getting "red" at the roulette
max_sbets = 4  # Maximum number of successful bets

hh = ss.binom(n, p)

total_p = 0
for k in range(1, max_sbets + 1):  # DO NOT FORGET THAT THE LAST INDEX IS NOT USED
    total_p += hh.pmf(k)
    
total_p * 100

8.733353573755974

In [150]:
# simulate 1 million tests of ten biased coin flips
tests = np.random.binomial(10, 0.15, int(1e6))

# proportion of tests that produced at least 3 heads
(tests >= 3).mean()

0.180196

## Data Cleaning

    Row = 0
    Col = 1
    
    For method:
    
    Row = 1
    Col = 0
    

In [ ]:
# use means to fill in missing values
df.fillna(df.mean(), inplace=True)

In [ ]:
# We replace NaN values with the previous value in the column
store_items.fillna(method = 'ffill', axis = 0)

In [ ]:
# We replace NaN values with the next value in the row
store_items.fillna(method = 'backfill', axis = 1)

In [ ]:
# linear interpolation is a method of curve fitting using linear polynomials to construct new data points 
# within the range of a discrete set of known data points.
# We replace NaN values by using linear interpolation using column values (Linear Interpolate)
store_items.interpolate(method = 'linear', axis = 0)

In [ ]:
# We drop any rows with NaN values
df.dropna(axis = 0)

In [ ]:
# We drop any columns with NaN values
store_items.dropna(axis = 1)

In [ ]:
# check for duplicates in the data
sum(df.duplicated())

# drop duplicates
df.drop_duplicates(inplace=True)

In [ ]:
for x, col in enumerate(df.columns):
    print(x, col)

In [ ]:
store_items.isnull().sum().sum()

## Model Building

In [ ]:
# Divide data into 60% training data and 40% test data, using a stratified split
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.4, random_state=0)
for train_index, test_index in sss.split(X, y):
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

In [ ]:
# Change sex to some numerical values
mapping = {'female': 1, 'male': 2}
X = X.replace({'Sex': mapping})

In [ ]:
sex = pd.get_dummies(data['Sex'], drop_first=True)

data = pd.concat([data, sex, embark, Pclass], axis=1)
data.drop(['Pclass','Name','Sex','Ticket','Embarked','Survived','PassengerId','Cabin'], axis=1, inplace=True)

In [ ]:
np.sum([(df['gender']=='female') & (df['major']=='Physics')])

In [ ]:
df['Start Time'] = pd.to_datetime(df['Start Time'], format='%Y%m%d %H:%M:%S', errors='ignore')

# extract hour from the Start Time column to create an hour column
df['hour'] = df['hour'] = df['Start Time'].dt.hour #.month / .weekday_name

# find the most common hour (from 0 to 23)
popular_hour = df['hour'].value_counts().idxmax()

In [151]:
# use the index of the months list to get the corresponding int
months = ['january', 'february', 'march', 'april', 'may', 'june']
month = months.index('february') + 1
month

2

In [ ]:
means_size_3 = []
for _ in range(10000):
    sample = np.random.choice(data, 3)
    means_size_3.append(sample.mean())
    
plt.hist(means_size_3);

In [ ]:
# print the column labels in the dataframe
for i, v in enumerate(data.columns):
    print(i, v)

## Numpy 

In [152]:
X = np.linspace(2,32,16).reshape(4,4)
print(X)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [155]:
X = np.linspace(3,32,16).reshape(4,4)
print(X)

[[ 3.          4.93333333  6.86666667  8.8       ]
 [10.73333333 12.66666667 14.6        16.53333333]
 [18.46666667 20.4        22.33333333 24.26666667]
 [26.2        28.13333333 30.06666667 32.        ]]


In [159]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = X = np.ones((4,4)) * np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [161]:
import pandas as pd

states = pd.Series([
    'California',
    'OH',
    'Michigan',
    'NY'])

def clean_state(state):
    
    if len(state) == 2:
        return state
    elif state == "California":
        return "CL"
    elif state == "Michigan":
        return "MC"

clean_state = states.apply(clean_state)
clean_state

0    CL
1    OH
2    MC
3    NY
dtype: object

In [168]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [163]:
np.diag(x)

array([0, 4, 8])

In [164]:
np.diag(x, k=1)

array([1, 5])

In [165]:
np.diag(x, k=-1)

array([3, 7])

In [166]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [171]:
np.fill_diagonal(x, 9)
x

array([[9, 1, 2],
       [3, 9, 5],
       [6, 7, 9]])

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.fill_diagonal.html